import type { AIMessage } from "./types";

/**
 * Fully offline fallback responder. Used whenever no AI provider key is
 * configured, so the product still works out of the box — clearly labeled
 * as demo/simulation everywhere it surfaces in the UI (see aiConnection
 * state in the store).
 */
export function demoRespond(userText: string, history: AIMessage[]): string {
  const text = userText.toLowerCase().trim();

  if (/^(hi|hello|hey|good (morning|evening|afternoon))\b/.test(text)) {
    return "Good to hear from you. All systems are functioning within optimal parameters. How may I assist?";
  }
  if (/diagnos/.test(text)) {
    return "Running comprehensive diagnostics. This may take a moment — I'll report each subsystem as it completes.";
  }
  if (/(status|how are (you|things))/.test(text)) {
    return "All systems operational. Neural core, voice, memory, security, quantum link, and tactical matrix are reporting green.";
  }
  if (/radar|threat|scan/.test(text)) {
    return "Tactical radar is active. I'm tracking a handful of simulated contacts — nothing classified as hostile at the moment.";
  }
  if (/memory/.test(text)) {
    return "Memory bank is within normal parameters. I can run an optimization pass if you'd like to reclaim some space.";
  }
  if (/who are you|what are you/.test(text)) {
    return "I'm J.A.R.V.I.S. — Just A Rather Very Intelligent System. I'm currently running in demo mode, without a connected AI backend, so my responses here are simulated rather than generated by a live model.";
  }
  if (/weather|time is it|news/.test(text)) {
    return "I don't have a live data connection in this environment, so I can't check that right now. Connect an AI provider or an n8n workflow to enable it.";
  }
  if (/thank/.test(text)) {
    return "Of course. Let me know if there's anything else you need.";
  }

  const fallbacks = [
    "Understood. I don't have a live AI backend connected right now, so I'm responding from a small set of demo behaviors — try 'run diagnostics', 'system status', or 'memory status'.",
    "Noted. This instance is running in simulation mode. Configure an AI provider key to enable full conversational responses.",
    "I've logged that. Without a connected model I can only offer scripted responses here — the interface and command system are fully live, though.",
  ];
  const seed = (userText.length + history.length) % fallbacks.length;
  return fallbacks[seed];
}

/** Splits a response into small chunks so demo mode still streams
 * progressively instead of appearing all at once. */
export function chunkForStreaming(text: string): string[] {
  return text.match(/\S+\s*/g) ?? [text];
}
